# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: test

on: [push]
        
jobs:

  readyGo:

    runs-on: ubuntu-latest
      
    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.1
          registry-url: https://registry.npmjs.org/
      
      - name: install packages
        run: |
          npm ci

      - name: lint code
        run: |
          npm run lint
